columns:
  satisfaction_level: float
  last_evaluation: float
  number_project: int 
  average_montly_hours: int  
  time_spend_company: int  
  Work_accident: int  
  promotion_last_5years: int  
  left: int
  sales: category
  salary: category 
  


numerical_columns:
  - satisfaction_level
  - last_evaluation
  - number_project
  - average_montly_hours
  - time_spend_company
  - Work_accident
  - promotion_last_5years



categorical_columns:
  - sales
  - salary


target_column: left


domain_value:
  sales:
    - sales
    - technical
    - support
    - IT
    - product_mng
    - marketing
    - RandD
    - accounting
    - hr
    - management
  salary:
    - low
    - medium
    - high